name: Pull Request into Master, Develop and Preprod

on:
  push:
    branches:
      - "CI-CD/test1"

jobs:
  #First job
  install-and-test:
    runs-on: ubuntu-latest

 steps: 
  build-android:
    needs: install-and-test
    uses: ./.github/workflows/android-build.yml
    with:
      environment: release
    secrets: inherit

  # Third Job
    build-ios:
      needs: install-and-test
      uses: ./.github/workflows/ios-build.yml
      with:
        environment: release
      secrets: inherit