name: Pull Request into Master, Develop and Preprod

on:
  push:
    branches:
      - "CI-CD/test1"

jobs:
  install-and-test:
    runs-on: ubuntu-latest

  build-android:
    needs: install-and-test
    uses: ./.github/workflows/android-build.yml
    with:
      environment: release
    secrets: inherit

  build-ios:
    needs: install-and-test
    uses: ./.github/workflows/ios-build.yml
    with:
      environment: release
    secrets: inherit
